name: Flyway Migrate

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'API/src/StellarPath.API/db/migrations/**'

jobs:
  migrate:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::574836245203:role/GitHubActionsOIDCRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: af-south-1

      - name: Verify AWS access
        run: |
          aws sts get-caller-identity
          aws s3 ls s3://stellar-path-s3-bucket/ || echo "Cannot list bucket contents"

      - name: Setup and initialize Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init and Output
        run: |
          cd terraform
          terraform init
          terraform output

      - name: Extract Terraform Outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - name: Print Terraform Outputs (Debug)
        run: |
          echo "RDS Endpoint: ${{ steps.tf-outputs.outputs.rds_endpoint }}"

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ steps.tf-outputs.outputs.rds_endpoint }}/stellarpath_db
          user: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          locations: filesystem:API/src/StellarPath.API/db/migrations
