name: Flyway Migrate

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'API/src/StellarPath.API/db/migrations/**'

jobs:
  migrate:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::574836245203:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Get Terraform Outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - name: Print Terraform Outputs
        run: |
          echo "RDS Endpoint: ${{ steps.tf-outputs.outputs.rds_endpoint }}"
          echo "ecr_repository_url: ${{ steps.tf-outputs.outputs.ecr_repository_url }}"
          echo "ecs_cluster_name: ${{ steps.tf-outputs.outputs.ecs_cluster_name }}"
          echo "ecs_service_name: ${{ steps.tf-outputs.outputs.ecs_service_name }}"
          
      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          
      - name: Run Flyway validate and migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ steps.tf-outputs.outputs.rds_endpoint }}/stellarpath_db
          user: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          locations: filesystem:API/src/StellarPath.API/db/migrations
